### ISSUE TITLE
Rename "Deactivate" to "Delete" in dashboards, graphs, targets

### ISSUE THREAD

**Issue by matthew-lucidchart** [lucidsoftware/nark#22]
Deactivate subscriptions means "turn it off for a little while". Delete subscriptions means "get rid of it".

That's not the same for dashboards, graphs, and targets.

**Comment by msiebert** [comment]
Is this not already done?

**Comment by matthew-lucidchart** [comment]
it's still showing on the manage graphs & targets page of a dashboard. although... now that I think of it, those aren't really deletes, since they're still there. That operation is more like a deactivate.

closing as already done.
